server:
  port: ${PORT:8080}

spring:
  application:
    name: valuebet-backend
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
  pattern:
    console: >-
      {"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%5p","thread":"%t","logger":"%logger","message":"%replace(%m%wEx){'\n','\\n'}","context":"%mdc"}

integration:
  the-odds-api:
    base-url: https://api.the-odds-api.com/v4
    sports-endpoint: /sports
    odds-endpoint: /sports/{sport}/odds
    default-sport: soccer_epl
    connect-timeout: 2s
    read-timeout: 5s
    retry:
      max-attempts: 3
      wait-duration: 500ms
    time-limiter:
      timeout-duration: 3s

valuebet:
  ingestion-horizon: 6h
  closing-line:
    priority-bookmakers:
      - bookmaker_1
      - bookmaker_2

security:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-this-secret}
    expiration: 24h

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:${DATABASE_JDBC_URL:jdbc:postgresql://gondola.proxy.rlwy.net:24130/railway}}
    username: ${DB_USERNAME:${DATABASE_USERNAME:${PGUSER:postgres}}}
    password: ${DB_PASSWORD:${DATABASE_PASSWORD:${PGPASSWORD:zlvqwOgoppApLuWjqLMPYsYhgkcAFXmH}}}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        sslmode: ${DB_SSLMODE:require}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
